### ISSUE TITLE
Auto disarm after 5 seconds of motors spinning on ground

### ISSUE THREAD

**Issue by priseborough** [3drobotics/ardupilot-solo#107]
https://3drsolo.atlassian.net/browse/FC-194

**Comment by bugobliterator** [comment]
Randy's new land and crash detector: https://github.com/3drobotics/ardupilot-solo/pull/106 should resolve this

**Comment by nick3dr** [comment]
Is this disarm after arming and not doing anything, or is this disarm after
crashing?

On Wed, Jul 15, 2015 at 8:22 PM, jschall <notifications@github.com> wrote:

> Closed #107 <https://github.com/3drobotics/ardupilot-solo/issues/107>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3drobotics/ardupilot-solo/issues/107#event-357123466>.
>



-- 
*Nick Speal*
Engineering Project Manager
*3D Robotics*

1608 4th Street, Suite 410
Berkeley, CA 94710
website <http://www.3dr.com/> | facebook
<http://www.facebook.com/3drobotics> | instagram
<http://www.instagram.com/3drobotics>

**Comment by rmackay9** [comment]
@nick3dr, this must be disarm after not doing anything..  the delay-after-crash is 2 seconds.
