### ISSUE TITLE
Delete closed branches

### ISSUE THREAD

**Issue by OXINARF** [3drobotics/ardupilot-solo#131]
Can't branches that have closed PRs be deleted here in GitHub? There's already 134 branches...
When a branch has a PR it can be deleted without any information being lost. Also if needed the branch can always be restored later.

**Comment by rmackay9** [comment]
What might help is if the developers (primarily Jon and Sid) made private forks of this ardupilot-solo repo and did their development there and then raised PRs from these personal repos into ardupilot-solo/master.
That would be more consistent with how the main ardupilot branch is utilised but really, it's up to Paul, Sid, Jon's better judgement about how best to work.

**Comment by OXINARF** [comment]
Randy that would be an option, the best option I think.

**Comment by wsilva32** [comment]
Agreed that this would have been a better way to go. I'm going through and cleaning up this repo now, so I'll be cleaning up branches soon as well. :)
