### ISSUE TITLE
The HDOP pre-arm check for Solo is now hard coded, whereas it used to be a parameter

### ISSUE THREAD

**Issue by IanHudsonP13** [3drobotics/ardupilot-solo#143]
In AP_NavEKF.cpp the HDOP pre-arm check when it was reinstated no longer uses the parameter GPS_HDOP_GOOD, this is a risk as Copter 3.3-rc8 has fixed the long standing problem of PDOP being reported as HDOP, so the pre-arm check that is hard coded would potentially be 40% higher than it should be if the fix is merged into the Solo Arducopter in future: https://github.com/diydrones/ardupilot/pull/2462

The hardcoding is currently using a "HDOP" of 250.
    // fail if satellite geometry is poor
    bool hdopFail = _ahrs->get_gps().get_hdop() > 250;

**Comment by wsilva32** [comment]
@IanHudsonP13 I believe we may have addressed this issue with this PR:
https://github.com/3drobotics/ardupilot-solo/pull/227
