### ISSUE TITLE
"Mode not armable"

### ISSUE THREAD

**Issue by squilter** [3drobotics/ardupilot-solo#151]
The RTL procedure is

RTL>land detected>disarm>change mode to loiter

For a split second after landing, the copter is disarmed in RTL.  It sends out a message saying "mode not armable".  This means that every time the copter lands int RTL, Tower will read that message, even though it looks like it's in Loiter when the user looks down at the screen.

**Comment by wsilva32** [comment]
@squilter The mode change to LOITER is enacted by software running on Solo's companion computer (SoloLink), not by APM. This message is sent out intentionally by APM as it will stay in RTL if SoloLink does not put it into LOITER.
