### ISSUE TITLE
open up beta testing to end users

### ISSUE THREAD

**Issue by franknitty69** [3drobotics/ardupilot-solo#185]
i think you guys should open up beta testing to end users. we are the ones in the field using solo in ways that a developer may not have envisioned, thus finding anomalies and edge cases. make it simple, survey for competence, nda, require a specific device, boom.

**Comment by joeynuggetz** [comment]
I agree. Count me in.

**Comment by IanHudsonP13** [comment]
It can only help find more bugs so it seems a sensible idea.

**Comment by franknitty69** [comment]
done and done. thanks.
