### ISSUE TITLE
Unresponsive after setting SERIAL1_PROTOCOL to "0"

### ISSUE THREAD

**Issue by rmackay9** [3drobotics/ardupilot-solo#215]
Even knowing that this was a bad idea I set SERIAL1_PROTOCOL to "0" on my solo.  Even after a factory reset I could not get the controller (or mission planner running on my desktop) to talk to the Solo.
I believe the only way to recover from this state is to disassemble the solo and connect to the USB port.

**Comment by johnfinley** [comment]
If that is the telemetry port, and that setting is disabling hw flow control (are both of those things right?), then it *may* be the case that you could disable flow control in /etc/sololink.conf and it would work well enough to avoid disassembly.

**Comment by peterbarker** [comment]
SERIAL4 also does mavlink.  I think that's the gimbal, and that's externally accessible.

**Comment by proficnc** [comment]
Load plane firmware via ssh, it uses USB to do that... Then go back to copter..

**Comment by DJISDKUser** [comment]
SERIAL2_PROTOCOL anything other than zero will do the same thing FWIW...
