### ISSUE TITLE
New Solo update seems to have 1.2.21

### ISSUE THREAD

**Issue by GPSFan** [3drobotics/ardupilot-solo#216]
3DR just released the 2.0.0 update.
Browsing through the /firmware folder I see the following 2 files.
-rw-r--r--  1 root root 702870 Feb  6 10:45 ArduCopter-1.2.21.px4
-rw-r--r--  1 root root  47327 Feb  6 10:45 gimbal_firmware_1.3.1.ax
Is the first of these related to the "BIG BOLD NOTICE" I see under releases?

solo-1.2.21
@jschall jschall released this 29 days ago · 2 commits to master since this release
NOTE: DO NOT FLY THIS WITH SHOT MANAGER VERSIONS PRIOR TO 2.0.0-4 - SHOTS WILL FLY INTO THE GROUND

I hope not.

Looks like a false alarm,
cat shotManager_version.py 
 # auto-generated Sat Feb  6 17:45:35 UTC 2016
VERSION = "shotmanager_v2.0.0-10"

**Comment by Gussy** [comment]
@GPSFan [semver](http://semver.org/) labels (x.x.x-**4**, x.x.x-**10**) get dropped on the release notes of each release. As you found out, 2.0.0 is *actually* 2.0.0-10 under the hood.
